/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.GestorConsulta;
import java.util.ArrayList;
import models.Test;

public class PantallaConsulta extends javax.swing.JFrame {
    
    
    public PantallaConsulta() {
        initComponents();
        setSize(1308,680);
        setResizable(false);
        setLocationRelativeTo(null);
        this.repaint(); 
        
        Test test = new Test();
       ArrayList llamadas = test.llamadas;
       ArrayList llamadasPeriodo = new ArrayList();
        
        
        GestorConsulta gestor = new GestorConsulta(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cal_fecha_inicio = new com.toedter.calendar.JDateChooser();
        lbl_fecha_inicio = new javax.swing.JLabel();
        lbl_fecha_fin = new javax.swing.JLabel();
        cal_fecha_fin = new com.toedter.calendar.JDateChooser();
        lbl_cliente = new javax.swing.JLabel();
        lbl_estado = new javax.swing.JLabel();
        lbl_duracion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_llamadas = new javax.swing.JTable();
        txt_cliente = new javax.swing.JTextField();
        txt_estado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_generar_csv = new javax.swing.JButton();
        txt_duracion = new javax.swing.JTextField();
        btn_confirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_respuestas_seleccionadas = new javax.swing.JTextArea();
        lbl_respuestas_seleccionadas = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_descripcion_encuesta = new javax.swing.JTextArea();
        lbl_descripcion_preguntas = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_descripcion_preguntas = new javax.swing.JTextArea();
        lbl_descripcion_encuesta = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_duracion1 = new javax.swing.JTextField();
        txt_duracion2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cal_fecha_inicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cal_fecha_inicioPropertyChange(evt);
            }
        });
        getContentPane().add(cal_fecha_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 165, 30));

        lbl_fecha_inicio.setText("Fecha Inicio");
        getContentPane().add(lbl_fecha_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        lbl_fecha_fin.setText("Fecha fin");
        getContentPane().add(lbl_fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));
        getContentPane().add(cal_fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 165, 30));

        lbl_cliente.setText("Cliente:");
        getContentPane().add(lbl_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        lbl_estado.setText("Estado:");
        getContentPane().add(lbl_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        lbl_duracion.setText("Duración:");
        getContentPane().add(lbl_duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, -1, -1));

        table_llamadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_llamadas);
        if (table_llamadas.getColumnModel().getColumnCount() > 0) {
            table_llamadas.getColumnModel().getColumn(0).setResizable(false);
            table_llamadas.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 790, 220));

        txt_cliente.setEditable(false);
        txt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 165, 30));

        txt_estado.setEditable(false);
        txt_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estadoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 165, 30));

        jPanel1.setBackground(new java.awt.Color(152, 202, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_generar_csv.setText("Generar CSV");
        btn_generar_csv.setEnabled(false);
        btn_generar_csv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generar_csvActionPerformed(evt);
            }
        });
        jPanel1.add(btn_generar_csv, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 100, 30));

        txt_duracion.setEditable(false);
        txt_duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_duracionActionPerformed(evt);
            }
        });
        jPanel1.add(txt_duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 165, 30));

        btn_confirmar.setText("Confirmar");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 100, 30));

        txt_respuestas_seleccionadas.setEditable(false);
        txt_respuestas_seleccionadas.setColumns(20);
        txt_respuestas_seleccionadas.setRows(5);
        jScrollPane1.setViewportView(txt_respuestas_seleccionadas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 310, 120));

        lbl_respuestas_seleccionadas.setText("Respuestas Seleccionadas");
        jPanel1.add(lbl_respuestas_seleccionadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 330, -1));

        txt_descripcion_encuesta.setEditable(false);
        txt_descripcion_encuesta.setColumns(20);
        txt_descripcion_encuesta.setRows(5);
        jScrollPane5.setViewportView(txt_descripcion_encuesta);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 310, 120));

        lbl_descripcion_preguntas.setText("Descripcion preguntas");
        jPanel1.add(lbl_descripcion_preguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 320, -1));

        txt_descripcion_preguntas.setEditable(false);
        txt_descripcion_preguntas.setColumns(20);
        txt_descripcion_preguntas.setRows(5);
        jScrollPane6.setViewportView(txt_descripcion_preguntas);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 290, 120));

        lbl_descripcion_encuesta.setText("Descripcion encuesta");
        jPanel1.add(lbl_descripcion_encuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 320, -1));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1140, 760));

        jPanel3.setBackground(new java.awt.Color(152, 202, 203));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ENCUESTA");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("CONSULTAR");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telefono.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 760));

        txt_duracion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_duracion1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_duracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 165, 30));

        txt_duracion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_duracion2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_duracion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 165, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cal_fecha_inicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cal_fecha_inicioPropertyChange


    }//GEN-LAST:event_cal_fecha_inicioPropertyChange

    private void txt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_clienteActionPerformed

    private void txt_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estadoActionPerformed

    private void btn_generar_csvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generar_csvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_generar_csvActionPerformed

    private void txt_duracion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_duracion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_duracion1ActionPerformed

    private void txt_duracion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_duracion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_duracion2ActionPerformed

    private void txt_duracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_duracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_duracionActionPerformed

    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_confirmarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cancelar;
    public javax.swing.JButton btn_confirmar;
    public javax.swing.JButton btn_generar_csv;
    private javax.swing.ButtonGroup buttonGroup1;
    public com.toedter.calendar.JDateChooser cal_fecha_fin;
    public com.toedter.calendar.JDateChooser cal_fecha_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbl_cliente;
    private javax.swing.JLabel lbl_descripcion_encuesta;
    private javax.swing.JLabel lbl_descripcion_preguntas;
    private javax.swing.JLabel lbl_duracion;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_fecha_fin;
    private javax.swing.JLabel lbl_fecha_inicio;
    private javax.swing.JLabel lbl_respuestas_seleccionadas;
    public javax.swing.JTable table_llamadas;
    public javax.swing.JTextField txt_cliente;
    public javax.swing.JTextArea txt_descripcion_encuesta;
    public javax.swing.JTextArea txt_descripcion_preguntas;
    public javax.swing.JTextField txt_duracion;
    public javax.swing.JTextField txt_duracion1;
    public javax.swing.JTextField txt_duracion2;
    public javax.swing.JTextField txt_estado;
    public javax.swing.JTextArea txt_respuestas_seleccionadas;
    // End of variables declaration//GEN-END:variables
}
